#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorpagina
cp *.* $build_folder
cd ..
cd $build_folder

#pandoc VoorpaginaCode.md -o ../../Boek/Boek_voorpagina_code.pdf
#pandoc VoorpaginaGitHub.md -o ../../Boek/Boek_voorpagina_github.pdf
pandoc Voorpagina1.md -o ../../Boek/Boek_voorpagina_1.pdf
pandoc Voorpagina2.md -o ../../Boek/Boek_voorpagina_2.pdf
pandoc Voorpagina3.md -o ../../Boek/Boek_voorpagina_3.pdf
#pandoc VoorpaginaStructuur.md -o ../../Boek/Boek_voorpagina_2_flow_input_structuur.pdf
#pandoc VoorpaginaOpenDag.md -o ../../Boek/Boek_voorpagina_open_dag.pdf
