#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorwoord                        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd BalNaarRechts                    ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd BalEeuwigNaarRechts              ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..
cd BalDieHorizontaalStuitert        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md; cd ..
cd Zwaartekracht                    ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_04.md; cd ..
cd WidthHeight                      ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_05.md; cd ..
cd Arrays1                          ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_06.md; cd ..
cd Arrays2                          ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_07.md; cd ..
cd PImage1                          ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_08.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md
cat README_04.md >> README.md; echo " " >> README.md
cat README_05.md >> README.md; echo " " >> README.md
cat README_06.md >> README.md; echo " " >> README.md
cat README_07.md >> README.md; echo " " >> README.md
cat README_08.md >> README.md; echo " " >> README.md

pandoc README.md -o boek.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

cp boek.pdf ../../Boek/Boek_structuur_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_2_flow_input_structuur.pdf Boek_structuur_zonder_voorpagina.pdf Boek_2_flow_input_structuur.pdf
rm Boek_structuur_zonder_voorpagina.pdf
