#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorwoord                ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd LineStroke               ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd BalEeuwigNaarRechts      ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..
cd RectFill                 ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md; cd ..
cd BalDieHorizontaalStuitert; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_04.md; cd ..
cd EllipseBackground        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_05.md; cd ..
cd BalDieSchuinStuitert     ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_06.md; cd ..
cd Text                     ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_07.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_04.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_05.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_06.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_07.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md

pandoc README.md -o Boek_2.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in
mv Boek_2.pdf ../../Boek/Boek_2_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_2.pdf Boek_2_zonder_voorpagina.pdf Boek_2.pdf

# Make booklet
bookletimposer -a Boek_2.pdf -o Boekje_2.pdf

rm Boek_2_zonder_voorpagina.pdf
