#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorwoord   ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd 3D1; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd 3D2; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..
cd 3D3; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md; cd ..
cd 3D4; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_04.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md
cat README_04.md >> README.md; echo " " >> README.md; echo "\pagebreak" >> README.md; echo " " >> README.md

pandoc README.md -o Boek_6.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in
mv Boek_6.pdf ../../Boek/Boek_6_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_6.pdf Boek_6_zonder_voorpagina.pdf Boek_6.pdf

# Make booklet
bookletimposer -a Boek_6.pdf -o Boekje_6.pdf

rm Boek_6_zonder_voorpagina.pdf
