#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorwoord                        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd ProcessingOpstartenOpCursusLaptop; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd EenMooiProgramma                 ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md

pandoc README.md -o boek.pdf
cp boek.pdf ../../Boek/Boek_introductie_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_intro.pdf Boek_introductie_zonder_voorpagina.pdf Boek_introductie.pdf
rm Boek_introductie_zonder_voorpagina.pdf
