#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorwoord                ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_00.md; cd ..
cd EenMooiProgramma         ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_01.md; cd ..
cd BalNaarRechts            ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_02.md; cd ..
cd BalEeuwigNaarRechts      ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_03.md; cd ..
cd BalDieHorizontaalStuitert; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_04.md; cd ..

cd $build_folder

cat README_00.md >> README.md; echo " " >> README.md
cat README_01.md >> README.md; echo " " >> README.md
cat README_02.md >> README.md; echo " " >> README.md
cat README_03.md >> README.md; echo " " >> README.md
cat README_04.md >> README.md; echo " " >> README.md

# Table of Content
# Code has highlights following the tango color scheme
# Thinner margin of 0.5 inch
# Do not cut code blocks
pandoc README.md -o boek.pdf --toc --toc-depth=1 --highlight-style=tango -V geometry:margin=0.5in

cp boek.pdf ../../Boek/Boek_open_dag_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_open_dag.pdf Boek_open_dag_zonder_voorpagina.pdf Boek_open_dag.pdf

# Make booklet
bookletimposer -a Boek_open_dag.pdf -o Boekje_open_dag.pdf

# Cleanup
rm Boek_open_dag_zonder_voorpagina.pdf

