#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi

cd ..
cd LessenProcessing
cd Voorpagina
cp *.* $build_folder
cd ..
cd $build_folder

pandoc Voorpagina1.md -o ../../Boek/Boek_voorpagina_1.pdf
pandoc Voorpagina2.md -o ../../Boek/Boek_voorpagina_2.pdf
pandoc Voorpagina3.md -o ../../Boek/Boek_voorpagina_3.pdf
pandoc Voorpagina4.md -o ../../Boek/Boek_voorpagina_4.pdf
pandoc Voorpagina5.md -o ../../Boek/Boek_voorpagina_5.pdf
pandoc Voorpagina6.md -o ../../Boek/Boek_voorpagina_6.pdf
