#!/bin/bash

# Concatenate all Markdown files first, convert those to one PDF

my_script_path=`realpath $0`
my_folder_path=`dirname $my_script_path`
build_folder=$my_folder_path/build
#echo $build_folder

rm -rf build
mkdir build

if [ ! -d $build_folder ]; then 
  echo "Error: failed to create build folder"
  exit 1
fi



cd ..
cd LessenProcessing
cd Voorwoord                        ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_90.md; cd ..
cd ProcessingOpstartenOpCursusLaptop; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_91.md; cd ..
cd GitHub                           ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_92.md; cd ..
cd GitHubPages                      ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_93.md; cd ..
cd ProcessingJS                     ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_94.md; cd ..
cd GitHubChat                       ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_95.md; cd ..
cd GitHubSamenwerken                ; cp *.* $build_folder; mv $build_folder/README.md $build_folder/README_96.md; cd ..

cd $build_folder
sed -e '$s/$/\n/' -s *.md > README.md

# sed -e '$s/$/\n/' -s *.md > all_content.md
# if [ ! -e gh-md-toc ]; then
#   wget https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc
#   chmod a+x gh-md-toc
# fi
# ./gh-md-toc all_content.md > toc.md
# cat toc.md > README.md
# cat all_content.md >> README.md

pandoc README.md -o boek.pdf
cp boek.pdf ../../Boek/Boek_github_zonder_voorpagina.pdf

cd ../../Boek
pdfunite Boek_voorpagina_github.pdf Boek_github_zonder_voorpagina.pdf Boek_github.pdf
rm Boek_github_zonder_voorpagina.pdf
